### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by rohitmucherla** [Big-Business-Brains/Prodactivity#8]
The readme steps are backwards for `pod install` and `npm install`

<img width="1248" alt="Screenshot 2020-06-01 10 29 40" src="https://user-images.githubusercontent.com/4967218/83425043-e3f32f80-a3f2-11ea-8565-56ccc59c98af.png">

I think on some OS's node modules need to come first. My pod install succeeded after I flipped the order

**Comment by rohitmucherla** [comment]
Last step in the readme to run the project needs to specify where to run npx command from for clarity

- [Clarify npx needs to be run from root folder ]

**Comment by rohitmucherla** [comment]
Clarify that Xcode needs to be running when you run npx otherwise it throws errors....at least it did on my machine

- [ ] Clarify npx should be run when Xcode is open (or at least preferably have Xcode open)

**Comment by rileydnorris** [comment]
Made these changes except the last, I'm not sure why that happened for you but it shouldn't be an issue
